default: &default
  :url: <%= ENV.fetch('OPENSEARCH_URL', 'http://localhost:9200') %>
  :transport_options:
    :request:
      :timeout: 5

development:
  <<: *default

test:
  <<: *default

production:
  :url: <%= CredentialsResolver.opensearch_url %>
