default: &default
  :url: <%= ENV.fetch('OPENSEARCH_URL', 'http://localhost:9200') %>
  :transport_options:
    :request:
      :timeout: 30
      :open_timeout: 30
      :read_timeout: 30
  :retry_on_failure: 5
  :request_timeout: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :transport_options:
    :request:
      :timeout: 60
      :open_timeout: 60
      :read_timeout: 60
  :retry_on_failure: 3
  :request_timeout: 60
