default: &default
  host: 'redis'

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("cosmetics-redis")["uri"] %>
