default: &default
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379') %>

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("cosmetics-queue")["uri"] %>
