# This configuration file is used for Scout APM.
# Environment variables can also be used to configure Scout. See our help docs at http://docs.scoutapm.com#environment-variables for more information.
common: &defaults

  # key: Your Organization key for Scout APM. Found on the settings screen.
  # - Default: none
  # key: From env var SCOUT_KEY

  # log_level: Verboseness of logs.
  # - Default: 'info'
  # - Valid Options: debug, info, warn, error
  # log_level: debug

  # name: Application name in APM Web UI
  # - Default: the application names comes from the Rails or Sinatra class name
  # name:

  # monitor: Enable Scout APM or not
  # - Default: none
  # - Valid Options: true, false
  monitor: true

  # Scout APM and Sentry both try to instrument `Net:HTTP` which causes a conflict
  # and results in `StackLevelTooDeep` exceptions. Disable Scout APM instrumentation
  # since they have not released a fix.
  disabled_instruments:
    - "NetHttp"

production:
  <<: *defaults

development:
  <<: *defaults
  monitor: false

test:
  <<: *defaults
  monitor: false

staging:
  <<: *defaults

pre-prod:
  <<: *defaults
