version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/cosmetics-web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/maintenance"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/cosmetics-web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: mimemagic
    versions:
    - 0.3.10
  - dependency-name: webmock
    versions:
    - 3.11.3
  - dependency-name: elasticsearch
    versions:
    - 7.11.0
  - dependency-name: okcomputer
    versions:
    - 1.18.3
