version: 2
updates:
  - package-ecosystem: bundler
    directory: "/cosmetics-web"
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
  - package-ecosystem: npm
    directory: "/cosmetics-web"
    schedule:
      interval: daily
    versioning-strategy: lockfile-only
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
