version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/cosmetics-web"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "nokogiri"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/cosmetics-web"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
