version: '3'

services:
  db:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"

  keycloak:
    env_file:
      - .env
      - .env.keycloak

  antivirus:
    volumes:
      - antivirus-sync:/antivirus:nocopy
      - bundle-cache:/usr/local/bundle

  maintenance:
    volumes:
      - maintenance-sync:/maintenance:nocopy

  cosmetics-web:
    command: bin/rails s -p 3002 -b 0.0.0.0
    ports:
      - "3002:3002"
    env_file:
      - .env
      - .env.keycloak.cosmetics
    volumes:
      - cosmetics-web-sync:/cosmetics-web:nocopy
      - bundle-cache:/usr/local/bundle
  cosmetics-worker:
    env_file:
      - .env
      - .env.antivirus
    volumes:
      - cosmetics-web-sync:/cosmetics-web:nocopy
      - bundle-cache:/usr/local/bundle

volumes:
  antivirus-sync:
    external: true
  maintenance-sync:
    external: true
  cosmetics-web-sync:
    external: true
