---
product_category:
  - Alarms
  - Baby/Children's Products
  - Clothing (inc. baby)
  - Cosmetics
  - Fancy Dress
  - Furniture & Furnishings
  - Lasers
  - Low Voltage Equipment (inc. plugs & sockets)
  - Measuring Instruments (inc. pressure)
  - Personal Protective Equipment (PPE)
  - Pyrotechnics
  - Sanitary Products
  - Small Electronics
  - Toys
  - White Goods
  - Other Product Type
