source "https://rubygems.org"

ruby File.read(".ruby-version").strip

# Will Paginate must be installed before elasticsearch
# https://github.com/elastic/elasticsearch-rails/issues/239
gem "will_paginate"

gem "axlsx", git: "https://github.com/randym/axlsx.git", ref: "c593a08"
gem "axlsx_rails"
gem "bootsnap", ">= 1.1.0"
gem "cf-app-utils"
gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "jbuilder", "~> 2.8"
gem "lograge"
gem "okcomputer"
gem "pg", "~> 1.1"
gem "pghero"
gem "puma", "~> 3.0"
gem "pundit"
gem "rails", "~> 5.2"
gem "redcarpet"
gem 'redis-rails'
gem "rubyzip", ">= 1.2.1"
gem "sentry-raven"
gem "slim-rails"
gem "slowpoke"
gem "strong_migrations"
gem "wicked"
gem "wicked_pdf"
gem "wkhtmltopdf-binary"

gem "shared-web", path: "./vendor/shared-web"


group :development, :test do
  gem "capybara"
  gem "roo", "~> 2.8.2"
  gem "rspec-mocks"
  gem "selenium-webdriver"

  gem "shared-web-dev", path: "./vendor/shared-web/dev"
end
