source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

# Specify your gem's dependencies in support_portal.gemspec.
gemspec

gem "sprockets-rails"
