---
hazard_type:
  - Asphyxiation
  - Burns
  - Chemical
  - Choking
  - Cuts
  - Damage to hearing
  - Damage to sight
  - Disturbance
  - Drowning
  - Electric shock
  - Electromagnetic
  - Energy consumption
  - Entrapment
  - Environment
  - Fire
  - Health risk
  - Incorrect measurement
  - Injuries
  - Microbiological
  - Security
  - Strangulation
  - Suffocation
  - Other
