---
product_category:
  - Chemical products
  - Childcare articles and children’s equipment
  - Clothing, textiles and fashion items
  - Communication and media equipment
  - Construction products
  - Cosmetics
  - Decorative articles
  - Eco-design
  - Electrical appliances and equipment
  - Explosive atmospheres equipment
  - Food-imitating products
  - Furniture
  - Gadgets
  - Gas appliances and components
  - Hand tools
  - Hobby / sports equipment
  - Jewellery
  - Kitchen / cooking accessories
  - Laser pointers
  - Lifts
  - Lighters
  - Lighting chains
  - Lighting equipment
  - Machinery
  - Measuring instruments
  - Motor vehicles
  - Pressure equipment / vessels
  - Protective equipment
  - Pyrotechnic articles
  - Rail and guided transport
  - Recreational crafts
  - Stationery
  - Toys
  - Waste
  - Other