require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 6

ExampleLength:
  Exclude:
    - 'spec/system/**/*'
