require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 6

ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*'

# Disable this so that we can use Capybara aliases like
# 'feature' and 'scenario' for more readable tests
Capybara/FeatureMethods:
  Enabled: false

# We can disable this as we’re using Capybara with RackTest which
# doesn’t support javascript, and so we we don’t need to use the
# asynchronous `have_current_path` matcher.
Capybara/CurrentPathExpectation:
  Enabled: false

# TODO: re-enable this after updating the helpers
Rails/HelperInstanceVariable:
  Enabled: false
