require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# TODO: re-enable this after updating the helpers
Rails/HelperInstanceVariable:
  Enabled: false

# Reasoning behind disabling this rule after originally trying to apply fixes in
# the codebase to pass Rubocop check with the rule enabled:
# - Makes testing harder as you cannot set up partially initialized objects for
#   unit testing a particular behavior on the object, forcing to do a full object
#   initialization.
# - Also makes it harder to do testing over an object not being #valid?, as will
#   raise an exception before we can assert over the object validation errors.
# - Found multiple instances when the validity of the resulting object after
#   creation/saving was being checked afterward, but Rubocop wasn't able to
#   identify it. I would end up having to manually disable/enable the rule in multiple
#   places.
# - With the "!" methods enforcing validations in every call, I see a good chance
#   to introduce bugs in the current codebase in situations where an object is
#   being built with multiple steps, being invalid until some stage. This would
#   now raise a runtime exception.
Rails/SaveBang:
  Enabled: false

RSpec/ExampleLength:
  Max: 6
  Exclude:
    - 'spec/system/**/*'
    - 'spec/smoke/**/*'
    - 'spec/features/**/*'
    - 'spec/services/notification_delete_service_spec.rb'
    - 'spec/services/notification_cloner/**/*'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/forms/responsible_persons/notifications/components/bulk_ingredient_upload_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*'

RSpec/Dialect:
  Enabled: true

RSpec/ExpectInHook:
  Exclude:
    - spec/features/account/change_name_spec.rb
    - spec/features/account/change_password_spec.rb
    - spec/features/account/change_email_spec.rb

RSpec/LetSetup:
  Exclude:
    - spec/features/account/change_name_spec.rb
    - spec/features/account/change_password_spec.rb

RSpec/MessageChain:
  Exclude:
    - spec/models/concerns/searchable_spec.rb

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'
    - 'spec/smoke/**/*'

# This rule is controversial.
# We have hundreds of violations of it in our codebase, and resolving them would
# require a lot of work refactoring our specs to break them down into separate
# test groups.
# The individual comments for disabling it in each case are quite noisy, so we're
# disabling the rule.
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - spec/requests/*
    - spec/search/*
    - spec/tasks/*

Rails/FilePath:
  Exclude:
    - spec/controllers/**/*

Naming/MethodParameterName:
  Exclude:
    - spec/support/**/*
