require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

# Disable this so that we can use Capybara aliases like
# 'feature' and 'scenario' for more readable tests
Capybara/FeatureMethods:
  Enabled: false

# We can disable this as we're using Capybara with RackTest which
# doesn't support javascript, and so we we don't need to use the
# asynchronous `have_current_path` matcher.
Capybara/CurrentPathExpectation:
  Enabled: false

Rails:
  Enabled: true

# TODO: re-enable this after updating the helpers
Rails/HelperInstanceVariable:
  Enabled: false

# Reasoning behind disabling this rule after orginally trying to apply fixes in
# the codebase to pass Rubocop check with the rule enabled:
# - Makes testing harder as you cannot setup partially initialized objects for
#   unit testing a particular behaviour on the object, forcing to do a full object
#   initialization.
# - Also makes harder to do testing over an object not being #valid?, as will
#   raise an exception before we can assert over the object validation errors.
# - Found multiple instances when the validity of the resulting object after
#   creation/saving was being checked afterwards, but Rubocop wasn't able to
#   identify it. I would end having to manually disable/enable the rule in multiple
#   places.
# - With the "!" methods enforcing validations in every call, I see a good chance
#   to introduce bugs in the current codebase in situations where an object is
#   being built with multiple steps, being invalid until some stage. This would
#   now raise a runtime exception.
Rails/SaveBang:
  Enabled: false

ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/features/**/*'
    - 'spec/services/notification_delete_service_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*'

RSpec/ExpectInHook:
  Exclude:
    - spec/features/account/change_mobile_number_spec.rb
    - spec/features/account/change_name_spec.rb
    - spec/features/account/change_password_spec.rb
    - spec/features/account/change_email_spec.rb

RSpec/LetSetup:
  Exclude:
    - spec/features/account/change_mobile_number_spec.rb
    - spec/features/account/change_name_spec.rb
    - spec/features/account/change_password_spec.rb

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 6

RSpec/ScatteredSetup:
  Exclude:
    - spec/features/account/change_mobile_number_spec.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - spec/requests/*

RSpec/FilePath:
  Exclude:
    - spec/controllers/**/*
