require: rubocop-rspec

inherit_gem:
  govuk-lint: configs/rubocop/all.yml

require: rubocop-performance

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 2

RSpec/NestedGroups:
  Max: 4

ExampleLength:
  Exclude:
    - 'spec/system/**/*'
