# Created from https://raw.githubusercontent.com/alphagov/govuk-lint/master/configs/scss_lint/gds-sass-styleguide.yml using http://sasstools.github.io/make-sass-lint-config/
options:
  formatter: stylish
  merge-default-rules: false

rules:
  bem-depth: 0
  border-zero: 0
  brace-style:
    - 2
    - allow-single-line: true
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline:
    - 2
    - include: true
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length: 0
  hex-notation:
    - 0
    - style: lowercase
  id-name-format:
    - 2
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 2
  leading-zero: 0
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 2
    - max-depth: 5
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 0
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  property-sort-order: 0
  property-units: 0
  quotes: 0
  shorthand-values:
    - 0
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens: 0
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 2
