source "https://rubygems.org"

ruby "~> 3.0"

gem "kaminari" # Must be loaded before ElasticSearch gems

# Needed a feature added into AASM master branch but still not tagged with a new version.
gem "aasm", "5.2.0"
# Needed to point active_hash to master version since the latest release is not compatible with Ruby 3 new keyword arg syntax.
# TODO: Switch back to semantic versioning when a version > 3.1.0 is released.
gem "active_hash", github: "zilkey/active_hash", ref: "1c95f99"
gem "activerecord-pg_enum"
gem "after_commit_everywhere"
gem "aws-sdk-s3", "~> 1.60.1"
gem "cf-app-utils", "~> 0.6"
gem "devise"
gem "devise-security"
# ES gems won't work with OpenSearch once ES and OS codebases start diverging:
# https://github.com/elastic/elasticsearch-rails/issues/1010
gem "elasticsearch", "7.17.1"
gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "govuk-design-system-rails", "~> 0.10.1"
gem "govuk_notify_rails", "~> 2.1.0"
gem "image_processing", "~> 1.2"
gem "interactor"
gem "jbuilder", "~> 2.9"
gem "lograge", "~> 0.11.2"
gem "mini_magick", "~> 4.9.4"
gem "net-imap", require: false # Needed for running Rails 6 with ruby 3.1
gem "net-pop", require: false # Needed for running Rails 6 with ruby 3.1
gem "net-smtp", require: false # Needed for running Rails 6 with ruby 3.1
gem "okcomputer", "~> 1.18.1"
gem "pg", "~> 1.2"
gem "puma", "~> 4.3"
gem "pundit", "~> 2.1.0"
gem "rails", "~> 6.1.6"
gem "request_store", "~> 1.5.0"
gem "rest-client", "~> 2.1.0"
gem "rotp", "~> 6.2.0"
gem "rqrcode", "~> 1.2.0"
gem "rubyzip", "~> 2.3.0"
gem "scout_apm"
gem "sentry-rails", "~> 5.7.0"
gem "sentry-ruby", "~> 5.7.0"
gem "sentry-sidekiq", "~> 5.7.0"
gem "sidekiq", "~> 5.2.7"
gem "sidekiq-cron", "~> 1.1.0"
gem "sidekiq-status", "~> 2.1.3"
gem "slowpoke", "~> 0.3.0"
gem "strong_migrations", "~> 0.7.9"
gem "webpacker", "~> 5.0"
gem "webrick", "~> 1.7"
gem "wicked", "~> 1.3.4"

group :production do
  gem "coverband", git: "https://github.com/OfficeForProductSafetyAndStandards/coverband.git"
end

group :development do
  gem "rails-erd"
end

group :development, :test do
  gem "brakeman", "~> 4.7.2"
  gem "capybara", "~> 3.36.0"
  gem "capybara-screenshot"
  gem "coveralls_reborn", "~> 0.22.0"
  gem "dotenv-rails", "~> 2.7.5"
  gem "factory_bot_rails"
  gem "faker"
  gem "launchy", "~> 2.4.3"
  gem "listen", "~> 3.7.0"
  gem "pry", "~> 0.14.1"
  gem "pry-byebug"
  gem "rails-controller-testing", "~> 1.0.4"
  gem "rspec-collection_matchers", "~> 1.2.0"
  gem "rspec-html-matchers", "~> 0.9.4"
  gem "rspec-rails", "~> 4.0.2"
  gem "rubocop", "~> 1.35.0"
  gem "rubocop-govuk", "~> 4.7"
  gem "rubocop-performance", "~> 1.12.0"
  gem "rubocop-rails", "~> 2.15.2"
  gem "rubocop-rspec", "~> 2.12.1"
  gem "selenium-webdriver", "~> 4.1"
  gem "simplecov", "~> 0.21.2"
  gem "simplecov-console", "~> 0.6.0"
  gem "simplecov-lcov", "~> 0.7.0"
  gem "solargraph", "~> 0.44.2"
  gem "solargraph-rails"
  gem "sprockets", "~> 3.7.2"
  gem "webmock", "~> 3.8"
end
