source "https://rubygems.org"


ruby File.read(".ruby-version").strip

gem "aasm"
gem "bootsnap", ">= 1.1.0"
gem "cf-app-utils"
gem "jbuilder", "~> 2.8"
gem "pg", "~> 1.1"
gem "puma", "~> 3.0"
gem "pundit"
gem "rails", "~> 5.2"
gem "rubyzip", ">= 1.2.1"
gem "slim-rails"
gem "strong_migrations"
gem "wicked"

gem "shared-web", path: "./vendor/shared-web"


group :development, :test do
  gem "factory_bot_rails"
  gem 'rails-controller-testing'
  gem 'rspec-collection_matchers'
  gem "rspec-rails"
  gem "rubocop-rspec"

  gem "shared-web-dev", path: "./vendor/shared-web/dev"
end
