source "https://rubygems.org"

ruby "~> 3.2.2"

gem "kaminari" # Must be loaded before ElasticSearch gems

gem "aasm", "~> 5.5"
gem "after_commit_everywhere", "~> 1.4"
gem "aws-sdk-s3", "~> 1.173"
gem "cf-app-utils", "~> 0.6"
gem "cssbundling-rails", "~> 1.4"
gem "devise", "~> 4.9"
gem "devise-security", "~> 0.18"
# TODO: Move to OpenSearch gems
# ES gems won't work with OpenSearch once ES and OS codebases start diverging:
# https://github.com/elastic/elasticsearch-rails/issues/1010
gem "elasticsearch", "7.17.10"
gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "flipper", "~> 1.3"
gem "flipper-active_record", "~> 1.3"
gem "flipper-ui", "~> 1.3"
gem "govuk-design-system-rails", "~> 0.10.5", github: "OfficeForProductSafetyAndStandards/govuk-design-system-rails"
gem "govuk_notify_rails", "~> 3.0"
gem "hashie", "~> 5.0"
gem "image_processing", "~> 1.13"
gem "interactor", "~> 3.1"
gem "jbuilder", "~> 2.13"
gem "jsbundling-rails", "~> 1.3"
gem "lograge", "~> 0.12"
gem "mini_magick", "< 5"
gem "net-imap", require: false # Needed for running Rails 6 with ruby 3.1
gem "net-pop", require: false # Needed for running Rails 6 with ruby 3.1
gem "net-smtp", require: false # Needed for running Rails 6 with ruby 3.1
gem "okcomputer", "~> 1.18.4"
gem "paper_trail", "~> 16.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.5"
gem "pundit", "~> 2.3"
gem "rails", ">= 7.1.0", "< 7.2.0"
gem "redis", "~> 5.2"
gem "request_store", "~> 1.6"
gem "rest-client", "~> 2.1"
gem "rotp", "~> 6.2"
gem "rqrcode", "~> 2.1"
gem "rubyzip", "~> 2.3"
gem "sassc-rails", "~> 2.1"
gem "scout_apm", "~> 5.4"
gem "sentry-rails", "~> 5.21"
gem "sentry-ruby", "~> 5.17"
gem "sentry-sidekiq", "~> 5.17"
gem "sidekiq", "~> 7.3"
gem "sidekiq-cron", "~> 2.0"
gem "sidekiq-status", "~> 3.0"
gem "sprockets", "~> 4.2"
gem "sprockets-rails", "~> 3.5", require: "sprockets/railtie"
gem "strong_migrations", "~> 2.1"
gem "webrick", "~> 1.9"
gem "wicked", "~> 2.0"

# OSU Support Portal engine
gem "support_portal", path: "support_portal"

group :development do
  gem "rails-erd"
end

group :development, :test do
  gem "brakeman"
  gem "capybara"
  gem "capybara-screenshot"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "listen"
  gem "pry"
  gem "pry-byebug"
  gem "rails-controller-testing"
  gem "rspec-collection_matchers"
  gem "rspec-html-matchers"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-govuk"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "selenium-webdriver"
  gem "simplecov"
  gem "simplecov-console"
  gem "simplecov-lcov"
  gem "solargraph"
  gem "solargraph-rails"
  gem "webmock"
end

gem "database_cleaner-active_record"

gem "graphiql-rails", group: :development
gem "graphql", "~> 2.4"
