module NotificationPropertiesHelper
  def get_notification_type_name(notification_type)
    NOTIFICATION_TYPE[notification_type&.to_sym]
  end

  def get_category_name(category)
    CATEGORY_NAME[category&.to_sym]
  end

  def get_frame_formulation_name(frame_formulation)
    FRAME_FORMULATION_NAME[frame_formulation&.to_sym]
  end

  def get_trigger_rules_question_name(trigger_rules_question)
    TRIGGER_RULES_QUESTION_NAME[trigger_rules_question&.to_sym]
  end

  def get_trigger_rules_short_question_name(trigger_rules_question)
    TRIGGER_RULES_SHORT_QUESTION_NAME[trigger_rules_question&.to_sym]
  end

  def get_trigger_rules_question_element_name(trigger_rules_question_element)
    TRIGGER_RULES_QUESTION_ELEMENT_NAME[trigger_rules_question_element&.to_sym]
  end

  def get_unit_name(unit)
    UNIT_NAME[unit&.to_sym]
  end

  def get_exposure_routes_names(exposure_routes)
    exposure_routes&.map(&method(:get_exposure_route_name))&.join(', ')
  end

  def get_exposure_route_name(exposure_route)
    EXPOSURE_ROUTE_NAME[exposure_route&.to_sym]
  end

  def get_exposure_condition_name(exposure_condition)
    EXPOSURE_CONDITION_NAME[exposure_condition&.to_sym]
  end

  def get_physical_form_name(physical_form)
    PHYSICAL_FORM[physical_form&.to_sym]
  end

  def get_special_applicator_name(special_applicator)
    SPECIAL_APPLICATOR[special_applicator&.to_sym]
  end

  NOTIFICATION_TYPE = {
      predefined: "Frame formulation",
      exact: "Exact concentration",
      range: "Concentration ranges"
  }.freeze

  CATEGORY_NAME = {
      skin_products: "Skin products",
      skin_care_products: "Skin care products",
      face_care_products_other_than_face_mask: "Face care products other than face mask",
      face_mask: "Face mask",
      eye_contour_products: "Eye contour products",
      lip_care_products: "Lip care products",
      hand_care_products: "Hand care products",
      foot_care_products: "Foot care products",
      body_care_products: "Body care products",
      external_intimate_care_products: "External intimate care products",
      chemical_exfoliation_products: "Chemical exfoliation products",
      mechanical_exfoliation_products: "Mechanical exfoliation products",
      skin_lightening_products: "Skin lightening products",
      other_skin_care_products: "Other skin care products",
      skin_cleansing_products: "Skin cleansing products",
      soap_products: "Soap products",
      bath_shower_products: "Bath / shower products",
      makeup_remover_products: "Make-up remover products",
      external_intimate_hygiene_products: "External Intimate hygiene products",
      other_skin_cleansing_products: "Other skin cleansing products",
      body_hair_removal_products: "Body hair removal products",
      chemical_depilatories: "Chemical depilatories",
      physical_epilation_products: "Physical  epilation products",
      other_body_hair_removal_products: "Other body hair removal products",
      bleach_for_body_hair_products: "Bleach for body hair products",
      bleach_for_body_hair: "Bleach for body hair",
      correction_of_body_odour_andor_perspiration: "Correction of body odour and/or perspiration",
      products_with_antiperspirant_activity: "Products with antiperspirant activity",
      products_without_antiperspirant_activity: "Products without antiperspirant activity",
      shaving_and_pre_after_shaving_products: "Shaving and pre- / after- shaving products",
      shaving_products: "Shaving products",
      pre_aftershaving_products: "Pre- / after-shaving products",
      other_shaving_and_pre_after_shaving_products: "Other shaving and pre- / after- shaving products",
      makeup_products: "Make-up products",
      foundation: "Foundation",
      concealer: "Concealer",
      other_face_makeup_products: "Other face make-up products",
      mascara: "Mascara",
      eye_shadow: "Eye shadow",
      eye_pencil: "Eye pencil",
      eye_liner: "Eye liner",
      other_eye_makeup_products: "Other eye make-up products",
      lip_stick: "Lip stick",
      lipstick_sealer: "Lipstick sealer",
      other_lip_makeup_products: "Other lip make-up products",
      body_or_face_paint_including_carneval_makeup: "Body or face paint , including carneval make-up",
      other_makeup_products: "Other make-up products",
      perfumes: "Perfumes",
      hydroalcoholic_perfumes: "Hydroalcoholic perfumes",
      non_hydroalcoholic_perfumes: "Non hydroalcoholic perfumes",
      sun_and_selftanning_products: "Sun and self-tanning products",
      before_and_after_sun_products: "Before and after sun products",
      sun_protection_products: "Sun protection products",
      selftanning_products: "Self-tanning products",
      other_sun_and_selftanning_products: "Other sun and self-tanning products",
      other_skin_products: "Other skin products",
      other_skin_products_child: "Other skin products",
      hair_and_scalp_products: "Hair and scalp products",
      hair_and_scalp_care_and_cleansing_products: "Hair and scalp care and cleansing products",
      shampoo: "Shampoo",
      hair_conditioner: "Hair conditioner",
      scalp_and_hair_roots_care_products: "Scalp and hair roots care products",
      antidandruff_products: "Antidandruff products",
      antihairloss_products: "Antihairloss products",
      other_hair_and_scalp_care_and_cleansing_products: "Other hair and scalp care and cleansing products",
      hair_colouring_products: "Hair colouring products",
      oxidative_hair_colour_products: "Oxidative hair colour products",
      nonoxidative_hair_colour_products: "Non-oxidative hair colour products",
      hair_bleaching_and_dye_remover_products: "Hair bleaching and dye remover products",
      other_hair_colouring_products: "Other hair colouring products",
      hair_styling_products: "Hair styling products",
      products_for_temporary_hair_styling: "Products for temporary hair styling",
      permanent_wave_products: "Permanent wave products",
      hair_relaxer_straightener_products: "Hair relaxer / straightener products",
      other_hair_styling_products: "Other hair styling products",
      other_hair_and_scalp_products: "Other hair and scalp products",
      hair_sun_protection_products: "Hair sun protection products",
      other_hair_and_scalp_products_child: "Other hair and scalp products",
      nail_and_cuticle_products: "Nail and cuticle products",
      nail_varnish_and_remover_products: "Nail varnish and remover products",
      nail_varnish_nail_makeup: "Nail varnish / Nail make-up",
      nail_varnish_remover: "Nail varnish remover",
      nail_varnish_thinner: "Nail varnish thinner",
      nail_bleach: "Nail bleach",
      other_nail_varnish_and_remover_products: "Other nail varnish and remover products",
      nail_care_nail_hardener_products: "Nail care / nail hardener products",
      nail_care_products: "Nail care products",
      nail_hardener: "Nail hardener",
      other_nail_care_nail_hardener_products: "Other nail care / nail hardener products",
      nail_glue_remover_products: "Nail glue remover products",
      nail_glue_remover: "Nail glue remover",
      other_nail_and_cuticle_products: "Other nail and cuticle products",
      cuticle_remover_softener: "Cuticle remover / softener",
      nail_sculpting_products: "Nail sculpting products",
      other_nail_and_cuticle_products_child: "Other nail and cuticle products",
      oral_hygiene_products: "Oral hygiene products",
      tooth_care_products: "Tooth care products",
      toothpaste: "Toothpaste",
      tooth_cleansing_powder_salt: "Tooth cleansing powder / salt",
      other_tooth_care_products: "Other tooth care products",
      mouth_wash_breath_spray: "Mouth wash / breath spray",
      mouth_wash: "Mouth wash",
      breath_spray: "Breath spray",
      other_mouth_wash_breath_spray_products: "Other mouth wash / breath spray products",
      tooth_whiteners: "Tooth whiteners",
      tooth_whiteners_child: "Tooth whiteners",
      other_oral_hygiene_products: "Other oral hygiene products",
      other_oral_hygiene_products_child: "Other oral hygiene products"
  }.freeze

  FRAME_FORMULATION_NAME = {
      skin_care_cream_lotion_gel: "Skin Care Cream, Lotion, Gel",
      skin_care_cream_lotion_gel_with_high_level_of_silicones: "Skin Care Cream, Lotion, Gel - With High Level Of Silicones",
      skin_care_cream_lotion_gel_with_high_level_of_humectants: "Skin Care Cream, Lotion, Gel - With High Level Of Humectants",
      skin_care_cream_lotion_gel_with_high_level_of_bulking_agents: "Skin Care Cream, Lotion, Gel - With High Level Of Bulking Agents",
      skin_care_cream_lotion_gel_with_high_level_of_fatty_compounds: "Skin Care Cream, Lotion, Gel - With High Level Of Fatty Compounds",
      skin_care_cream_lotion_gel_with_high_level_of_uv_filters: "Skin Care Cream, Lotion, Gel - With High Level Of Uv Filters",
      skin_gel_hydroalcoholic_based: "Skin Gel (Hydro-Alcoholic Based)",
      skin_oil: "Skin Oil",
      tonic_cosmetic_water: "Tonic, Cosmetic Water",
      skin_care_silicone_based: "Skin Care  (Silicone Based)",
      petroleum_jelly: "Petroleum Jelly",
      other_face_care_products_other_than_face_mask: "Other Face Care Products Other Than Face Mask",
      other_face_mask_products: "Other Face Mask Products",
      other_eye_contour_products: "Other Eye Contour Products",
      lip_care: "Lip Care",
      other_lip_care_products: "Other Lip Care Products",
      other_hand_care_products: "Other Hand Care Products",
      other_foot_care_products: "Other Foot Care Products",
      skin_care_cream_lotion_gel_with_high_level_of_perfume: "Skin Care Cream, Lotion, Gel - With High Level Of Perfume",
      zinc_oxide_based_cream: "Zinc Oxide Based Cream",
      talcum_powder_powder_or_pressed: "Talcum Powder (Powder Or Pressed)",
      other_body_care_products: "Other Body Care Products",
      external_intimate_care_products: "External Intimate Care Products",
      chemical_exfoliation_products: "Chemical Exfoliation Products",
      other_chemical_exfoliation_products: "Other Chemical Exfoliation Products",
      skin_cleansing_cream_lotion_scrub_gel: "Skin Cleansing Cream, Lotion, Scrub, Gel",
      body_scrub_gel_cream: "Body Scrub (Gel, Cream)",
      other_mechnical_exfoliation_products: "Other Mechnical Exfoliation Products",
      other_skin_lightening_products: "Other Skin Lightening Products",
      foaming_skin_cleanser: "Foaming Skin Cleanser",
      foaming_skin_cleanser_with_high_level_of_oils_andor_humectants: "Foaming Skin Cleanser - With High Level Of Oils And/Or Humectants",
      gentle_cleansing_gel: "Gentle Cleansing Gel",
      other_skin_care_products: "Other Skin Care Products",
      soap_toilet: "Soap - Toilet",
      liquid_soap: "Liquid Soap",
      other_soap_products: "Other Soap Products",
      bath_and_shower_gel_cream_milk_paste: "Bath And Shower Gel, Cream, Milk, Paste",
      slightly_foaming_shower_cream_milk: "Slightly Foaming Shower Cream, Milk",
      bath_salts_cubes: "Bath Salts / Cubes",
      bath_and_shower_oil_including_bath_beads: "Bath And Shower Oil (Including Bath Beads)",
      footbath: "Footbath",
      other_bath_shower_products: "Other Bath / Shower Products",
      makeup_remover_non_foaming_cleanser_including_twophase_products: "Make-Up Remover - Non Foaming Cleanser (Including Two-Phase Products)",
      makeup_remover_non_foaming_oil_cleanser: "Make-Up Remover - Non Foaming Oil Cleanser",
      other_makeup_remover_products: "Other Make-Up Remover Products",
      other_external_intimate_hygiene_products: "Other External Intimate Hygiene Products",
      other_skin_cleansing_products: "Other Skin Cleansing Products",
      chemical_depilatory_cream_gel: "Chemical Depilatory - Cream, Gel",
      other_chemical_depilatory_products: "Other Chemical Depilatory Products",
      physical_depilation_product_wax_resin_based: "Physical Depilation Product - Wax Resin Based",
      physical_depilation_product_wax_sugar_based: "Physical Depilation Product - Wax Sugar Based",
      other_physical_epilation_products: "Other Physical Epilation Products",
      other_body_hair_removal_products: "Other Body Hair Removal Products",
      bleach_for_body_hair: "Bleach For Body Hair",
      other_bleach_for_body_hair_products: "Other Bleach For Body Hair Products",
      antiperspirant_aerosol_spray_with_antiperspirant_salt: "Antiperspirant Aerosol Spray (With Antiperspirant Salt)",
      antiperspirant_rollon_with_antiperspirant_salt: "Antiperspirant Roll-On (With Antiperspirant Salt)",
      antiperspirant_stick_with_antiperspirant_salt: "Antiperspirant Stick (With Antiperspirant Salt)",
      antiperspirant_liquid_squeeze_pack_or_pump_spray: "Antiperspirant Liquid Squeeze Pack Or Pump Spray",
      antiperspirant_cream: "Antiperspirant Cream",
      other_products_with_antiperspirant_activity: "Other Products With Antiperspirant Activity",
      deodorant_aerosol_spray_without_antiperspirant_salt: "Deodorant Aerosol Spray (Without Antiperspirant Salt)",
      deodorant_rollon_without_antiperspirant_salt: "Deodorant Roll-On (Without Antiperspirant Salt)",
      deodorant_stick_without_antiperspirant_salt: "Deodorant Stick (Without Antiperspirant Salt)",
      deodorant_liquid_squeeze_pack_or_pump_spray: "Deodorant Liquid Squeeze Pack Or Pump Spray",
      other_products_without_antiperspirant_activity: "Other Products Without Antiperspirant Activity",
      shaving_cream: "Shaving Cream",
      brushless_shaving_cream: "Brushless Shaving Cream",
      shave_gel: "Shave Gel",
      shaving_gel_post_foaming: "Shaving Gel (Post Foaming)",
      shaving_foam_aerosol: "Shaving Foam Aerosol",
      shaving_soapstick: "Shaving Soap/Stick",
      other_shaving_and_pre_after_shaving_products: "Other shaving and pre- / after- shaving products",
      aftershave_balm: "Aftershave Balm",
      aftershave_lotion: "Aftershave Lotion",
      other_pre_aftershaving_products: "Other Pre- / After-Shaving Products",
      foundation_and_blusher_liquid_cream_foam: "Foundation And  Blusher (Liquid, Cream, Foam)",
      foundation_anhydrous: "Foundation - Anhydrous",
      foundation_concealer_solid: "Foundation / Concealer (Solid)",
      other_foundation_products: "Other Foundation Products",
      concealer_cream: "Concealer Cream",
      concealer_stick: "Concealer Stick",
      lipstick_lip_cream_including_concealer_stickcream: "Lipstick / Lip Cream  (Including Concealer Stick/Cream)",
      other_concealer_products: "Other Concealer Products",
      other_face_makeup_products: "Other Face Make-Up Products",
      mascara_regular: "Mascara - Regular",
      mascara_waterproof: "Mascara - Waterproof",
      mascara_cake: "Mascara (Cake)",
      other_mascara_products: "Other Mascara Products",
      eye_shadow_blusher_and_liner_powder: "Eye Shadow, Blusher And Liner (Powder)",
      eye_shadow_and_blusher_cream: "Eye Shadow And Blusher (Cream)",
      eye_shadow_and_blusher_anhydrous_cream_stick_powder_: "Eye Shadow And Blusher - Anhydrous (Cream, Stick, Powder, ,,,)",
      other_eye_shadow_products: "Other Eye Shadow Products",
      eye_pencil: "Eye Pencil",
      other_eye_pencil_products: "Other Eye Pencil Products",
      eye_liner_regular_liquid_cream: "Eye Liner - Regular (Liquid, Cream)",
      eye_liner_waterproof_liquid_cream_paste: "Eye Liner - Waterproof (Liquid, Cream, Paste)",
      eye_liner_cake: "Eye Liner (Cake)",
      other_eye_liner_products: "Other Eye Liner Products",
      lip_and_eye_fix_regular: "Lip And Eye Fix Regular",
      eye_fix_anhydrous: "Eye Fix - Anhydrous",
      other_eye_makeup_products: "Other Eye Make-Up Products",
      other_lip_stick_products: "Other Lip Stick Products",
      lipstick_sealer_lip_coat: "Lipstick Sealer / Lip Coat",
      other_lipstick_sealer_products: "Other Lipstick Sealer Products",
      lip_colour_and_glosserbalm: "Lip Colour And Glosser/Balm",
      lip_pencil: "Lip Pencil",
      lip_ink_pencil: "Lip Ink  (Pencil)",
      lip_ink_liquid: "Lip Ink  (Liquid)",
      other_lip_makeup_products: "Other Lip Make-Up Products",
      body_glitter: "Body Glitter",
      other_body_or_face_paint_products: "Other Body Or Face Paint Products",
      face_powder: "Face Powder",
      other_makeup_products: "Other Make-Up Products",
      perfume_eau_de_cologne_eau_de_toilette_eau_de_parfum_extrait_de_parfum_parfum: "Perfume (Eau De Cologne, Eau De Toilette, Eau De Parfum, Extrait De Parfum, Parfum)",
      other_hydroalcoholic_perfumes: "Other Hydroalcoholic Perfumes",
      perfumed_powder_loose_or_pressed: "Perfumed Powder (Loose OR Pressed)",
      solid_perfume_paste_waxe_: "Solid Perfume (Paste, Waxe, ,,,)",
      perfumed_skin_oil: "Perfumed Skin Oil",
      other_non_hydroalcoholic_perfumes: "Other Non Hydroalcoholic Perfumes",
      other_before_and_after_sun_products: "Other Before And After Sun Products",
      sunscreen_cream_lotion: "Sunscreen Cream, Lotion",
      sunscreen_oil: "Sunscreen Oil",
      sunscreen_stick: "Sunscreen Stick",
      sunscreen_hydrogel: "Sunscreen Hydrogel",
      sunscreen_gel_oil_based: "Sunscreen Gel (Oil Based)",
      other_sun_protection_products: "Other Sun Protection Products",
      self_tan_lotion_cream: "Self Tan - Lotion, Cream",
      self_tan_lotion_gel: "Self Tan - Lotion, Gel",
      other_selftanning_products: "Other Self-Tanning Products",
      other_sun_and_selftanning_products: "Other Sun And Self-Tanning Products",
      other_skin_products: "Other Skin Products",
      shampoo_liquid_cream_paste: "Shampoo - Liquid, Cream, Paste",
      soap_shampoo: "Soap Shampoo",
      shampoo_plus_conditioner: "Shampoo Plus Conditioner",
      other_shampoo_products: "Other Shampoo Products",
      hair_conditioner: "Hair Conditioner",
      hair_conditioner_silicone_based: "Hair Conditioner (Silicone Based)",
      hair_scalp_care_lotion: "Hair / Scalp Care Lotion",
      hair_scalp_biphase_lotion: "Hair / Scalp Biphase Lotion",
      other_hair_conditioner_products: "Other Hair Conditioner Products",
      other_scalp_and_hair_roots_care_products: "Other Scalp And Hair Roots Care Products",
      shampoo_liquid_cream_paste_child: "Shampoo - Liquid, Cream, Paste",
      other_antidandruff_products: "Other Antidandruff Products",
      other_antihairloss_products: "Other Antihairloss Products",
      other_hair_and_scalp_care_and_cleansing_products: "Other Hair And Scalp Care And Cleansing Products",
      hair_colorant_permanent_oxidative_type_type_1_two_components_colorant_part: "Hair Colorant (Permanent, Oxidative Type) - Type 1 : Two Components - Colorant Part",
      hair_colorant_permanent_oxidative_type_type_2_two_components_colorant_part_with_high_level_of_oils: "Hair Colorant (Permanent, Oxidative Type) - Type 2 :Two Components - Colorant Part With High Level Of Oils",
      hair_colorant_permanent_oxidative_type_type_3_three_components_colorant_part_a: "Hair Colorant (Permanent, Oxidative Type) - Type 3 : Three Components - Colorant Part A",
      hair_colorant_permanent_oxidative_type_type_3_three_components_colorant_part_b: "Hair Colorant (Permanent, Oxidative Type) - Type 3 : Three Components - Colorant Part B",
      hair_colorant_permanent_oxidative_type_type_1_two_or_three_components_oxidative_part: "Hair Colorant (Permanent, Oxidative Type) - Type 1 : Two Or Three Components - Oxidative Part",
      hair_colorant_permanent_oxidative_type_type_2_two_or_three_components_oxidative_part_with_high_level_of_oils: "Hair Colorant (Permanent, Oxidative Type) - Type 2 : Two Or Three Components - Oxidative Part With High Level Of Oils",
      other_oxidative_hair_colour_products: "Other Oxidative Hair Colour Products",
      hair_colorant_temporary_shampoo: "Hair Colorant (Temporary) - Shampoo",
      hair_colorant_temporary_foam_lotion: "Hair Colorant (Temporary) - Foam, Lotion",
      hair_colorant_temporary_or_semipermanent_liquid_cream_foam: "Hair Colorant (Temporary Or Semi-Permanent) - Liquid, Cream, Foam",
      other_nonoxidative_hair_colour_products: "Other Non-Oxidative Hair Colour Products",
      dye_remover_reducing_type_part_a: "Dye Remover (Reducing Type) - Part A",
      dye_remover_reducing_type_part_b: "Dye Remover (Reducing Type) - Part B",
      dye_remover_oxidative_type_part_a: "Dye Remover (Oxidative Type)  -  Part A",
      dye_remover_oxidative_type_part_b: "Dye Remover (Oxidative Type)  -  Part B",
      skin_dyeremoving_cleanser_reducing_type: "Skin Dye-Removing Cleanser (Reducing Type)",
      hair_bleach_powder: "Hair Bleach - Powder",
      hair_bleach_paste: "Hair Bleach - Paste",
      hair_bleach_oxidative_part_type_1: "Hair Bleach - Oxidative Part - Type 1",
      hair_bleach_oxidative_part_type_2: "Hair Bleach - Oxidative Part - Type 2",
      hair_bleach_alkaline_part: "Hair Bleach - Alkaline Part",
      other_hair_bleaching_and_dye_remover_products: "Other Hair Bleaching And Dye Remover Products",
      other_hair_colouring_products: "Other Hair Colouring Products",
      hair_styling_cream_paste_gum_pomade_paste_waxe_: "Hair Styling Cream / Paste (Gum, Pomade, Paste, Waxe, ,,,)",
      hair_shine_wax_or_brilliantine: "Hair Shine Wax Or Brilliantine",
      hair_styling_lotion: "Hair Styling Lotion",
      setting_lotion_including_coloured_setting_lotions: "Setting Lotion (Including Coloured Setting Lotions)",
      hair_shine_styling_gel: "Hair Shine / Styling Gel",
      hair_foam: "Hair Foam",
      hair_spray_aerosol: "Hair Spray - Aerosol",
      hair_spray_pump_spray: "Hair Spray - Pump Spray",
      hair_shine_spray_aerosol: "Hair Shine Spray - Aerosol",
      other_products_for_temporary_hair_styling: "Other Products For Temporary Hair Styling",
      permanent_wave_lotion_single_component_based_on_reducing_agents: "Permanent Wave Lotion - Single Component - Based On Reducing Agents",
      permanent_wave_lotion_twocomponent_based_on_hydrogen_peroxide_and_reducing_agents_part_a: "Permanent Wave Lotion - Two-Component - Based On Hydrogen Peroxide And Reducing Agents - Part A",
      permanent_wave_lotion_twocomponent_based_on_hydrogen_peroxide_and_reducing_agents_part_b: "Permanent Wave Lotion - Two-Component - Based On Hydrogen Peroxide And Reducing Agents - Part B",
      permanent_wave_lotion_twocomponent_based_on_reducing_agents_part_a: "Permanent Wave Lotion - Two-Component - Based On Reducing Agents - Part A",
      permanent_wave_lotion_twocomponent_based_on_reducing_agents_part_b: "Permanent Wave Lotion - Two-Component - Based On Reducing Agents - Part B",
      permanent_wave_neutraliser_hair_straightener_relaxer_neutraliser_liquid_cream: "Permanent Wave Neutraliser / Hair Straightener (Relaxer) Neutraliser - Liquid, Cream",
      other_permanent_wave_products: "Other Permanent Wave Products",
      hair_straightener_relaxer_type_1: "Hair Straightener (Relaxer) - Type 1",
      hair_straightener_relaxer_type_2_part_a: "Hair Straightener (Relaxer) - Type 2 - Part A",
      hair_straightener_relaxer_type_2_part_b: "Hair Straightener (Relaxer) - Type 2 - Part B",
      hair_straightener_relaxer_type_3: "Hair Straightener (Relaxer) - Type 3",
      other_hair_relaxer_straightener_products: "Other Hair Relaxer / Straightener Products",
      other_hair_styling_products: "Other Hair Styling Products",
      other_hair_sun_protection_products: "Other Hair Sun Protection Products",
      other_hair_and_scalp_products: "Other Hair And Scalp Products",
      nail_varnish: "Nail Varnish",
      nail_white_pencil: "Nail White Pencil",
      other_nail_varnish_nail_makeup: "Other Nail Varnish / Nail Make-Up",
      nail_varnish_remover: "Nail Varnish Remover",
      nail_varnish_thinner: "Nail Varnish Thinner",
      nail_bleach: "Nail Bleach",
      other_nail_varnish_and_remover_products: "Other Nail Varnish And Remover Products",
      nail_conditioner_oil_based: "Nail Conditioner (Oil Based)",
      other_nail_care_products: "Other Nail Care Products",
      nail_hardener: "Nail Hardener",
      other_nail_care_nail_hardener_products: "Other Nail Care / Nail Hardener Products",
      nail_glue_remover: "Nail Glue Remover",
      cuticle_remover_softener: "Cuticle Remover / Softener",
      nail_sculpting_products: "Nail Sculpting Products",
      other_nail_and_cuticle_products: "Other Nail And Cuticle Products",
      toothpaste: "Toothpaste",
      other_toothpaste_products: "Other Toothpaste Products",
      tooth_cleansing_powder_salt: "Tooth Cleansing Powder / Salt",
      other_tooth_care_products: "Other Tooth Care Products",
      mouthwash: "Mouthwash",
      mouthwash_concentrate: "Mouthwash (Concentrate)",
      other_mouth_wash_products: "Other Mouth Wash Products",
      breath_spray_pump_spray: "Breath Spray (Pump Spray)",
      others_breath_spray_products: "Others Breath Spray Products",
      other_mouth_wash_breath_spray_products: "Other Mouth Wash / Breath Spray Products",
      tooth_whiteners: "Tooth Whiteners",
      other_oral_hygiene_products: "Other Oral Hygiene Products",
      dry_shampoo: "Dry Shampoo",
      syndet_bar_soap: "Syndet Bar Soap",
      combo_bar_soap: "Combo Bar Soap"
  }.freeze

  TRIGGER_RULES_QUESTION_NAME = {
      please_specify_the_percentage_weight_of_ethanol: "Please specify the percentage weight of ethanol.",
      please_specify_the_percentage_weight_of_isopropanol: "Please specify the percentage weight of isopropanol.",
      please_specify_the_inci_name_and_concentration_of_the_antidandruff_agents_if_antidandruff_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of the antidandruff agent(s).  If antidandruff agent(s) are not present in the cosmetic product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_the_antihair_loss_agents_if_antihair_loss_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of the anti-hair loss agent(s). If anti-hair loss agent(s) are not present in the cosmetic product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_the_antipigmenting_and_depigmenting_agents_if_antipigmenting_and_depigmenting_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of the anti-pigmenting and depigmenting agent(s). If anti-pigmenting and depigmenting agent(s) are not present in the cosmetic product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_chemical_exfoliating_agents_if_chemical_exfoliating_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of chemical exfoliating agents. If chemical exfoliating agent(s) are not present in the cosmetic product, then 'not applicable' must be checked.",
      please_specify_the_exact_content_of_vitamin_a_or_its_derivatives_for_the_whole_product_if_the_level_of_vitamin_a_or_any_of_its_derivatives_does_not_exceed_020_calculated_as_retinol_or_if_the_amount_does_not_exceed_009_grams_calculated_as_retinol_or_if_vitamin_a_or_any_of_its_derivatives_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the exact content of vitamin A or its derivatives for the whole product. If the level of vitamin A or any of its derivatives does not exceed 0.20% (calculated as retinol) or if the amount does not exceed 0.09 grams (calculated as retinol) or if vitamin A or any of its derivatives are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_the_concentration_of_xanthine_derivatives_eg_caffeine_theophylline_theobromine_plant_extracts_containing_xanthine_derivatives_eg_paulinia_cupana_guarana_extractspowders_if_xanthine_derivatives_are_not_present_or_present_below_05_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Please specify the INCI name and the concentration of xanthine derivatives (e.g. caffeine, theophylline, theobromine, plant extracts containing xanthine derivatives e.g. paulinia cupana (guarana) extracts/powders). If xanthine derivatives are not present or present below 0.5% in the cosmetic product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_the_cationic_surfactants_with_two_or_more_chain_lengths_below_c12_if_the_surfactant_is_used_for_non_preservative_purpose_if_cationic_surfactants_with_two_or_more_chain_lengths_below_c12_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of the cationic surfactants with two or more chain lengths below C12 if the surfactant is used for non preservative purpose. If cationic surfactants with two or more chain lengths below C12 are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_each_propellant_if_propellants_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of each propellant. If propellants are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_concentration_of_hydrogen_peroxide_if_hydrogen_peroxide_is_not_present_in_the_product_then_not_applicable_must_be_checked_: "Please specify the concentration of hydrogen peroxide. If hydrogen peroxide is not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_the_concentration_of_the_compounds_that_release_hydrogen_peroxide_if_compounds_releasing_hydrogen_peroxide_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and the concentration of the compounds that release hydrogen peroxide. If compounds releasing hydrogen peroxide are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_each_reducing_agent_if_reducing_agents_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of each reducing agent. If reducing agent(s) are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_each_persulfate_if_persulfates_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of each persulfate. If persulfate(s) are not present in the product, then 'not applicable' must be checked.",
      please_specify_the_inci_name_and_concentration_of_each_straightening_agent_if_straightening_agents_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please specify the INCI name and concentration of each straightening agent. If straightening agent(s) are not present in the product, then 'not applicable' must be checked.",
      please_indicate_the_total_concentration_of_inorganic_sodium_salts_if_inorganic_sodium_salts_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please indicate the total concentration of inorganic sodium salts. If inorganic sodium salts are not present in the product, then 'not applicable' must be checked.",
      please_indicate_the_concentration_of_fluoride_compounds_calculated_as_fluorine_if_fluoride_compounds_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Please indicate the concentration of fluoride compounds (calculated as Fluorine). If fluoride compounds are not present in the product, then 'not applicable' must be checked.",
      is_the_ph_of_the_component_lower_than_3_or_higher_than_10: "Is the pH of the component lower than 3 or higher than 10?",
      please_indicate_the_total_level_of_essential_oils_camphor_menthol_or_eucalyptol_if_essential_oils_camphor_menthol_or_eucalyptol_are_not_present_in_the_product_or_if_the_level_of_essential_oils_camphor_menthol_or_eucalyptol_does_not_exceed_05_then_not_applicable_must_be_checked: "Please indicate the total level of essential oils, camphor, menthol or eucalyptol. If essential oils, camphor, menthol or eucalyptol are not present in the product or if the level of essential oils, camphor, menthol or eucalyptol does not exceed 0.5%, then 'not applicable' must be checked.",
      please_indicate_the_name_and_the_quantity_of_each_essential_oil_camphor_menthol_or_eucalyptol_if_no_individual_essential_oil_camphor_menthol_or_eucalyptol_are_present_with_a_level_higher_than_05_015_in_case_of_camphor_then_not_applicable_must_be_checked: "Please indicate the name and the quantity of each essential oil, camphor, menthol or eucalyptol. If no individual essential oil, camphor, menthol or eucalyptol are present with a level higher than 0.5% (0.15 % in case of camphor), then 'not applicable' must be checked.",
      please_indicate_the_total_concentration_of_inorganic_sodium_salts: "Please indicate the total concentration of inorganic sodium salts.",
      please_indicate_the_ph_of_the_hair_dye_component: "Please indicate the pH of the hair dye component.",
      please_indicate_the_ph_of_the_mixed_hair_dye_product: "Please indicate the pH of the mixed hair dye product.",
      please_indicate_the_ph: "Please indicate the pH",
      please_indicate_the_ph_of_the_mixed_product_: "Please indicate the pH of the mixed product. ",
      do_the_components_of_the_product_need_to_be_mixed: "Do the components of the product need to be mixed?",
      please_indicate_the_inci_name_and_concentration_of_each_alkaline_agent_including_ammonium_hydroxide_liberators: "Please indicate the INCI name and concentration of each alkaline agent (including ammonium hydroxide liberators)"
  }.freeze

  TRIGGER_RULES_SHORT_QUESTION_NAME = {
      please_specify_the_percentage_weight_of_ethanol: "Ethanol",
      please_specify_the_percentage_weight_of_isopropanol: "Isopropanol",
      please_specify_the_inci_name_and_concentration_of_the_antidandruff_agents_if_antidandruff_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Anti-dandruff agents",
      please_specify_the_inci_name_and_concentration_of_the_antihair_loss_agents_if_antihair_loss_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Anti-hair loss agents",
      please_specify_the_inci_name_and_concentration_of_the_antipigmenting_and_depigmenting_agents_if_antipigmenting_and_depigmenting_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Anti-pigmenting and depigmenting agents",
      please_specify_the_inci_name_and_concentration_of_chemical_exfoliating_agents_if_chemical_exfoliating_agents_are_not_present_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Chemical exfoliating agents",
      please_specify_the_exact_content_of_vitamin_a_or_its_derivatives_for_the_whole_product_if_the_level_of_vitamin_a_or_any_of_its_derivatives_does_not_exceed_020_calculated_as_retinol_or_if_the_amount_does_not_exceed_009_grams_calculated_as_retinol_or_if_vitamin_a_or_any_of_its_derivatives_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Vitamin A or its derivatives",
      please_specify_the_inci_name_and_the_concentration_of_xanthine_derivatives_eg_caffeine_theophylline_theobromine_plant_extracts_containing_xanthine_derivatives_eg_paulinia_cupana_guarana_extractspowders_if_xanthine_derivatives_are_not_present_or_present_below_05_in_the_cosmetic_product_then_not_applicable_must_be_checked: "Xanthine derivatives",
      please_specify_the_inci_name_and_concentration_of_the_cationic_surfactants_with_two_or_more_chain_lengths_below_c12_if_the_surfactant_is_used_for_non_preservative_purpose_if_cationic_surfactants_with_two_or_more_chain_lengths_below_c12_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Cationic surfactants",
      please_specify_the_inci_name_and_concentration_of_each_propellant_if_propellants_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Propellant",
      please_specify_the_concentration_of_hydrogen_peroxide_if_hydrogen_peroxide_is_not_present_in_the_product_then_not_applicable_must_be_checked_: "Hydrogen peroxide",
      please_specify_the_inci_name_and_the_concentration_of_the_compounds_that_release_hydrogen_peroxide_if_compounds_releasing_hydrogen_peroxide_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Compounds releasing hydrogen peroxide",
      please_specify_the_inci_name_and_concentration_of_each_reducing_agent_if_reducing_agents_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Reducing agents",
      please_specify_the_inci_name_and_concentration_of_each_persulfate_if_persulfates_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Persulfates",
      please_specify_the_inci_name_and_concentration_of_each_straightening_agent_if_straightening_agents_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Straightening agents",
      please_indicate_the_total_concentration_of_inorganic_sodium_salts_if_inorganic_sodium_salts_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Inorganic sodium salts",
      please_indicate_the_concentration_of_fluoride_compounds_calculated_as_fluorine_if_fluoride_compounds_are_not_present_in_the_product_then_not_applicable_must_be_checked: "Fluoride compounds",
      is_the_ph_of_the_component_lower_than_3_or_higher_than_10: "pH lower than 3 or higher than 10",
      please_indicate_the_total_level_of_essential_oils_camphor_menthol_or_eucalyptol_if_essential_oils_camphor_menthol_or_eucalyptol_are_not_present_in_the_product_or_if_the_level_of_essential_oils_camphor_menthol_or_eucalyptol_does_not_exceed_05_then_not_applicable_must_be_checked: "Total concentration of essential oils, camphor, menthol or eucalyptol",
      please_indicate_the_name_and_the_quantity_of_each_essential_oil_camphor_menthol_or_eucalyptol_if_no_individual_essential_oil_camphor_menthol_or_eucalyptol_are_present_with_a_level_higher_than_05_015_in_case_of_camphor_then_not_applicable_must_be_checked: "Essential oils, camphor, menthol or eucalyptol",
      please_indicate_the_total_concentration_of_inorganic_sodium_salts: "Inorganic sodium salts",
      please_indicate_the_ph_of_the_hair_dye_component: "Hair dye component pH",
      please_indicate_the_ph_of_the_mixed_hair_dye_product: "pH of mixed components",
      please_indicate_the_ph: "	Exact pH",
      please_indicate_the_ph_of_the_mixed_product_: "pH of mixed components",
      do_the_components_of_the_product_need_to_be_mixed: "Components mixed",
      please_indicate_the_inci_name_and_concentration_of_each_alkaline_agent_including_ammonium_hydroxide_liberators: "Alkaline agents"
  }.freeze

  TRIGGER_RULES_QUESTION_ELEMENT_NAME = {
      ethanol: "ethanol",
      propanol: "propanol",
      inciname: "inciName",
      incivalue: "inciValue",
      value: "value",
      ph: "ph",
      concentration: "concentration",
      minrangevalue: "minRangeValue",
      maxrangevalue: "maxRangeValue"
  }.freeze

  UNIT_NAME = {
      less_than_01_percent: "≤ 0.1",
      greater_than_01_less_than_1_percent: "> 0.1 and ≤ 1",
      greater_than_1_less_than_5_percent: "> 1 and ≤ 5",
      greater_than_5_less_than_10_percent: "> 5 and ≤ 10",
      greater_than_10_less_than_25_percent: "> 10 and ≤ 25",
      greater_than_25_less_than_50_percent: "> 25 and ≤ 50",
      greater_than_50_less_than_75_percent: "> 50 and ≤ 75",
      greater_than_75_less_than_100_percent: "> 75 and ≤ 100"
  }.freeze

  EXPOSURE_ROUTE_NAME = {
      dermal: "Dermal",
      oral: "Oral",
      inhalation: "Inhalation"
  }.freeze

  EXPOSURE_CONDITION_NAME = {
      rinse_off: "Rinse off",
      leave_on: "Leave on"
  }.freeze

  PHYSICAL_FORM = {
      solid_or_pressed_powder: "Solid/pressed powder",
      loose_powder: "Loose powder",
      cream_or_paste: "Cream/paste",
      liquid: "Liquid",
      foam: "Foam",
      spray: "Spray",
      other_physical_form: "Other"
  }.freeze

  SPECIAL_APPLICATOR = {
      wipe_sponge_patch_pad: "Wipe/sponge/patch/pad",
      encapsulated_products: "Encapsulated products",
      pressurised_spray_container: "Pressurised spray container",
      pressurised_container_non_spray_product: "Pressurised container - non spray product",
      other_special_applicator: "Other"
  }.freeze
end
