#!/bin/bash
set -ex

# Create the database and user required by Keycloak

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $KEYCLOAK_DATABASE;
  CREATE USER $KEYCLOAK_USERNAME WITH ENCRYPTED PASSWORD '$KEYCLOAK_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DATABASE TO $KEYCLOAK_USERNAME;
EOSQL
