name: Delete review app

on:
  pull_request:
    types: [closed]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  cleanup_reviewapp:
    name: Delete review app
    runs-on: ubuntu-latest
    env:
      SPACE: int
      CF_USERNAME: ${{ secrets.PaaSUsernameInt }}
      CF_PASSWORD: ${{ secrets.PaaSPasswordInt }}
    steps:
    - uses: actions/checkout@v1
      if: github.event.pull_request.merged == true

    - name: Install cf7 client
      env:
        CF_CLI_VERSION: 7.0.0-beta.25
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}" | tar -zx -C /tmp
        sudo cp /tmp/cf7 /usr/local/bin/cf7

    - name: Delete review app
      run: |
        cf7 api api.london.cloud.service.gov.uk
        cf7 auth
        cf7 target -o 'beis-opss' -s $SPACE
        cf7 delete -f -r cosmetics-pr-$PR_NUMBER
        cf7 delete-service -f cosmetics-review-redis-$PR_NUMBER
        cf7 logout

    - name: Deactivate Github deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GithubApiDeploymentToken }}
      run: |
        source cosmetics-web/deploy-github-functions.sh
        gh_deploy_deactivate_dangling review-app-$PR_NUMBER
