name: Tests

on: [push]

env:
  SEARCH_HOST: search
  SUBMIT_HOST: submit
  DATABASE_URL: postgres://localhost:5432/cosmetics_test
  PGHOST: localhost
  PGUSER: postgres

jobs:
  ruby:
    name: "Ruby"
    runs-on: ubuntu-latest

    # Example for can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      elasticsearch:
        image: elasticsearch:6.7.2
        ports: ["9200:9200"]
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.x
    # required to compile pg ruby gem
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - uses: actions/cache@v1
      with:
        path: cosmetics-web/vendor/bundle
        key: ${{ runner.OS }}-gems
        restore-keys: |
          ${{ runner.OS }}-gems
          ${{ runner.OS }}-gems-
          ${{ runner.OS }}-
    - uses: actions/cache@v1
      with:
        path: cosmetics-web/node_modules
        key: ${{ runner.OS }}-node
        restore-keys: |
          ${{ runner.OS }}-node
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install Ruby Gems
      env:
        RAILS_ENV: test
      run: |
        cd cosmetics-web
        gem install bundler -v 1.17.3
        bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - name: Install JavaScript dependencies
      env:
        RAILS_ENV: test
      run: |
        cd cosmetics-web
        npm install yarn -g
        yarn install
        bin/webpack
    - name: Prepare application database
      env:
        RAILS_ENV: test
      run: |
        cd cosmetics-web
        bin/rails db:setup
    - name: Run Tests
      env:
        KEYCLOAK_AUTH_URL: ${{ secrets.KeycloakAuthUrl }}
        KEYCLOAK_CLIENT_ID: ${{ secrets.KeycloakClientId }}
        KEYCLOAK_CLIENT_SECRET: ${{ secrets.KeycloakClientSecret }}
        KEYCLOAK_USER_ID: ${{ secrets.KeycloakUserId }}
        KEYCLOAK_POISON_CENTER_USER_ID: ${{ secrets.KeycloakPoisonCenterUserId }}
        KEYCLOAK_USER_PASSWORD: ${{ secrets.KeycloakUserPassword }}
        ELASTICSEARCH_URL: localhost
        RAILS_ENV: test
        CI: true
        COVERALLS_REPO_TOKEN: ${{secrets.CoverallsToken}}
      run: |
        echo $BRANCH_NAME
        cd cosmetics-web
        #GIT_BRANCH=${GITHUB_REF##*/} bundle exec rspec spec/models
        GIT_BRANCH=debug-coveralls-test bundle exec rspec spec/models
