inherit_gem:
  govuk-lint: configs/rubocop/all.yml

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true