source "https://rubygems.org"

ruby File.read(".ruby-version").strip

# Will Paginate must be installed before elasticsearch
# https://github.com/elastic/elasticsearch-rails/issues/239
gem "will_paginate"

gem "active_hash"
gem "ar_merge"
gem "aws-sdk-s3"
gem "axlsx", git: "https://github.com/randym/axlsx.git", ref: "c593a08"
gem "axlsx_rails"
gem "bootsnap", ">= 1.1.0"
gem "cf-app-utils"
gem "clamby"
gem "companies-house-rest"
gem "elasticsearch-model"
gem "elasticsearch-rails"
gem "govuk_notify_rails"
gem "jbuilder", "~> 2.8"
gem "keycloak"
gem "lograge"
gem "mini_magick"
gem "pg", "~> 1.1"
gem "pghero"
gem "puma", "~> 3.0"
gem "pundit"
gem "rails", "~> 5.2"
gem "redcarpet"
gem "rubyzip", ">= 1.2.1"
gem "sass-rails", "~> 5.0"
gem "sentry-raven"
gem "sidekiq"
gem "sidekiq-cron"
gem "slim-rails"
gem "slowpoke"
gem "strong_migrations"
gem "uglifier", ">= 1.3.0"
gem "wicked"
gem "wicked_pdf"
gem "wkhtmltopdf-binary"

gem 'shared-web', path: './vendor/shared-web'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platform: :mri
  gem "capybara"
  gem "debase"
  gem "roo", "~> 2.7.0"
  gem "rspec-mocks"
  gem "ruby-debug-ide"
  gem "selenium-webdriver"
  gem "govuk-lint"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "listen", "~> 3.1.5"
  gem "solargraph"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
